networks:
  grafana-prometheus:
    external: false

# 创建挂载卷
volumes:
  grafana-storage: {}

services:
  # 容器命名方式为：${name}-demo

  # 启动grafana
  grafana-demo:
    image: grafana/grafana
    container_name: grafana-demo
    ports:
      - "9080:3000"
    networks:
      - grafana-prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      TZ: Asia/Shanghai
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: false

  # 启动prometheus
  prometheus-demo:
    image: prom/prometheus
    container_name: prometheus-demo
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    environment:
      TZ: Asia/Shanghai
    ports:
      - "9090:9090"
    networks:
      - grafana-prometheus

  # 启动node-exporter
  node-exporter-demo:
    image: prom/node-exporter
    container_name: node-exporter-demo
    environment:
      TZ: Asia/Shanghai

    # bridge网桥模式
    networks:
      - grafana-prometheus
    # 监听容器本身，不需要挂载本地目录 /proc和/sys
    ports:
      - "9100:9100"

    # host宿主机模式
#    network_mode: host
#    pid: host
#    command:
#      - '--path.rootfs=/host'

