networks:
  grafana-prometheus:
    external: false

services:
  # 容器命名方式为：${name}-demo

  # 启动grafana
  grafana-demo:
    image: grafana/grafana:latest
    container_name: grafana-demo
    ports:
      - "9080:3000"
    networks:
      - grafana-prometheus
    volumes:
      - ./volumes/grafana/provisioning/etc/datasources:/etc/grafana/provisioning/datasources:ro
      - ./volumes/grafana/provisioning/etc/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./volumes/grafana/provisioning/var/dashboards:/var/lib/grafana/dashboards:ro
    environment:
      TZ: Asia/Shanghai
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_USERS_ALLOW_SIGN_UP: false

  # 启动prometheus
  prometheus-demo:
    image: prom/prometheus
    container_name: prometheus-demo
    command:
      - "--config.file=/etc/prometheus/prometheus.yml" # prometheus配置文件
      - "--storage.tsdb.path=/prometheus" # prometheus数据存储路径
    volumes:
      # 设置目录挂载
      - ./volumes/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    environment:
      TZ: Asia/Shanghai
    ports:
      - "9090:9090"
    networks:
      - grafana-prometheus

  # 启动node-exporter
  node-exporter-demo:
    image: prom/node-exporter
    container_name: node-exporter-demo
    environment:
      TZ: Asia/Shanghai

    # bridge网桥模式
    networks:
      - grafana-prometheus
    # 监听容器本身，不需要挂载本地目录 /proc和/sys
    ports:
      - "9100:9100"

    # host宿主机模式
#    network_mode: host
#    pid: host
#    command:
#      - '--path.rootfs=/host'

