networks:
  grafana-prometheus:
    external: false

# 创建挂载卷
volumes:
  grafana-storage: {}

services:
  # 容器命名方式为：${name}-demo

  # 启动grafana
  grafana-demo:
    image: grafana/grafana
    container_name: grafana-demo
    ports:
      - "9080:3000"
    networks:
      - grafana-prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      TZ: Asia/Shanghai
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: false

  # 启动prometheus
  prometheus-demo:
    image: prom/prometheus
    container_name: prometheus-demo
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    environment:
      TZ: Asia/Shanghai
    ports:
      - "9090:9090"
    networks:
      - grafana-prometheus

  # 启动node-exporter
  # 该模式仅支持在Linux中运行
  # 容器内端口9100
  node-exporter-demo:
    image: prom/node-exporter
    container_name: node-exporter-demo
    environment:
      TZ: Asia/Shanghai
    # host宿主机模式
    network_mode: host
    # 容器与宿主机共享进程号
    pid: host
    # https://github.com/prometheus/node_exporter
    volumes:
      - '/:/host:ro,rslave'
    command:
      - '--path.rootfs=/host'

    # Linux中文件系统目录: /proc /sys
#    volumes:
#      - /proc:/host/proc:ro
#      - /sys:/host/sys:ro
#      - /:/rootfs:ro
